#!/usr/bin/env bash
# AutoDrama · AutoDL 一键环境脚本（5090 32G / Ubuntu）
#
# 用法（按需组合）：
#   bash setup_autodl.sh                      # 基础：ffmpeg + 依赖 + 目录 + .env（无卡开机也能装）
#   bash setup_autodl.sh --gpu                # 加装 torch/diffusers（跑渲染必需）
#   bash setup_autodl.sh --gpu --video wan    # 再下载 Wan2.2 图生视频（推荐先跑通它）
#   bash setup_autodl.sh --gpu --video h3     # 或下载 MiniMax H3（FP16 约 65G，注意显存）
#   bash setup_autodl.sh --gpu --models       # 额外下载 SDXL 出图模型
#   bash setup_autodl.sh --gpu --video wan --models   # 一次配齐
#
# 设计原则：
#   - 代码放系统盘，模型与素材放 /root/autodl-tmp（数据盘，关机不丢）
#   - pip 多镜像自动回退（某个源被限流时不会卡死）
#   - API Key 用 read -s 交互式写入：不回显、不进命令历史、不进 GitHub
set -e

DATA_DIR=/root/autodl-tmp
WITH_GPU=0
WITH_MODELS=0
WITH_TTS=0
VIDEO=""
while [ $# -gt 0 ]; do
  case "$1" in
    --gpu)    WITH_GPU=1 ;;
    --models) WITH_GPU=1; WITH_MODELS=1 ;;
    --video)  WITH_GPU=1; VIDEO="${2:-wan}"; shift ;;
    --tts)    WITH_GPU=1; WITH_TTS=1 ;;
  esac
  shift || true
done

SUDO=""
[ "$(id -u)" -ne 0 ] && SUDO="sudo"

# AutoDL 镜像的 conda 不在非登录 shell 的 PATH 里，这里自动找回来
if ! command -v python3 >/dev/null 2>&1; then
  for _p in /root/miniconda3/bin /opt/conda/bin /usr/local/miniconda3/bin; do
    if [ -x "$_p/python3" ]; then
      export PATH="$_p:$PATH"
      echo "已把 $_p 加入 PATH"
      break
    fi
  done
fi

echo "==> 0/6 环境自检"
python3 --version || { echo "缺少 python3"; exit 1; }
if command -v nvidia-smi >/dev/null 2>&1; then
  nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
else
  echo "未检测到 GPU（无卡开机模式）：装依赖没问题，但生成阶段必须开 GPU 实例"
fi

echo "==> 1/6 安装 ffmpeg 与中文字体（合成必需；不装中文字体字幕会画不出汉字）"
if command -v ffmpeg >/dev/null 2>&1; then
  echo "ffmpeg 已存在：$(ffmpeg -version | head -1)"
else
  $SUDO apt-get update -qq && $SUDO apt-get install -y -qq ffmpeg fonts-noto-cjk
fi

echo "==> 2/6 安装 Python 核心依赖"
pip_install() {
  for m in https://pypi.tuna.tsinghua.edu.cn/simple \
           https://mirrors.aliyun.com/pypi/simple/ \
           https://pypi.org/simple; do
    if python3 -m pip install "$@" -i "$m"; then return 0; fi
    echo "    镜像 $m 失败，换下一个"
  done
  return 1
}
python3 -m pip install --upgrade pip -q 2>/dev/null || true
pip_install -r requirements.txt

if [ "$WITH_GPU" = "1" ]; then
  echo "==> 3/6 安装 GPU 渲染依赖（torch/diffusers，较大）"
  # insightface / onnxruntime-gpu 在某些算力（如 sm_120）上会编译失败，
  # 它们只服务于候选自动选优，装不上不该中断整条流水线。
  pip_install -r requirements-gpu.txt \
    || echo "[warn] 部分 GPU 依赖未装上（不影响出图，候选自动选优会退化为人工选）"
  echo "    校验核心渲染依赖……"
  python3 -c "import diffusers, transformers, accelerate" \
    || { echo "核心渲染依赖缺失，请手动 pip install diffusers transformers accelerate"; exit 1; }
  echo "    核心依赖 OK"
else
  echo "==> 3/6 跳过 GPU 依赖（跑渲染前需要：bash setup_autodl.sh --gpu）"
fi

echo "==> 4/6 准备数据盘目录（关机不丢）"
mkdir -p "$DATA_DIR/models" "$DATA_DIR/cache" "$DATA_DIR/repos"

echo "==> 5/6 生成 .env"
FONT=""
for f in /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc \
         /usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc \
         /usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc; do
  [ -f "$f" ] && FONT="$f" && break
done
[ -z "$FONT" ] && FONT=$(fc-list :lang=zh 2>/dev/null | head -1 | cut -d: -f1)

if [ ! -f .env ]; then
  {
    echo "# Generated by setup_autodl.sh —— 本文件已被 .gitignore 屏蔽，存镜像前请删除"
    echo "AUTODRAMA_DATA_ROOT=$DATA_DIR"
    echo "AUTODRAMA_MODEL_DIR=$DATA_DIR/models"
    echo "AUTODRAMA_FONT=$FONT"
    echo "DEEPSEEK_BASE_URL=https://api.deepseek.com"
    echo "DEEPSEEK_MODEL=deepseek-flash"
    echo "DEEPSEEK_MAX_TOKENS=16384"
    echo "AUTODRAMA_VIDEO=worker"
    echo "AUTODRAMA_VIDEO_BACKEND=${VIDEO:-wan}"
  } > .env
  echo "已生成 .env（字体：$FONT）"
else
  echo ".env 已存在，跳过；如需改视频后端可手动编辑 AUTODRAMA_VIDEO_BACKEND"
fi

if ! grep -q "DEEPSEEK_API_KEY=sk" .env 2>/dev/null; then
  if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
    # 非交互：DEEPSEEK_API_KEY=sk-xxx bash setup_autodl.sh --gpu
    echo "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY" >> .env
    echo "已用环境变量中的 DeepSeek Key 写入 .env"
  else
    echo ""
    echo "请粘贴 DeepSeek API Key（输入不回显，只写入本机 .env，不会进 GitHub）："
    read -s DSK
    if [ -n "$DSK" ]; then
      echo "DEEPSEEK_API_KEY=$DSK" >> .env
      echo "已写入 .env"
    else
      echo "未输入，稍后可手动：echo 'DEEPSEEK_API_KEY=sk-xxx' >> .env"
    fi
    unset DSK
  fi
fi

echo "==> 6/6 模型下载"
MODEL_DIR="$DATA_DIR/models"

if [ -n "$VIDEO" ]; then
  pip_install modelscope
  echo "下载视频模型：$VIDEO（到 $MODEL_DIR，耗时较长，可用后台方式跑）"
  python3 - "$VIDEO" "$MODEL_DIR" <<'PY'
import os, sys
kind, root = sys.argv[1], sys.argv[2]
targets = {
    # 图生视频：优先 fp8/bf16 变体，32G 显存别下 FP16 全量
    "wan": ["Wan-AI/Wan2.2-I2V-A14B"],
    "h3":  ["MiniMaxAI/MiniMax-H3"],
}
try:
    from modelscope import snapshot_download
    for mid in targets.get(kind, []):
        try:
            p = snapshot_download(mid, cache_dir=root)
            print("downloaded:", p)
        except Exception as e:
            print(f"[warn] {mid} 下载失败：{e}")
            print(f"      可手动执行：modelscope download --model {mid} --local_dir {root}")
except ImportError:
    print("modelscope 未安装，可手动下载后把目录写进 AUTODRAMA_VIDEO_MODEL")
PY

  if [ "$VIDEO" = "h3" ]; then
    echo "同步 MiniMax H3 官方推理代码（脚本接口常变，故 worker 支持命令模板覆盖）"
    if [ ! -d "$DATA_DIR/repos/MiniMax-H3" ]; then
      git clone --depth 1 https://github.com/MiniMaxAI/MiniMax-H3 \
        "$DATA_DIR/repos/MiniMax-H3" 2>/dev/null \
        || echo "[warn] clone 失败，请手动下载后设置 AUTODRAMA_H3_DIR"
    fi
    {
      echo "AUTODRAMA_H3_DIR=$DATA_DIR/repos/MiniMax-H3"
      echo "AUTODRAMA_H3_MODEL=$MODEL_DIR/MiniMax-H3"
    } >> .env
  else
    echo "AUTODRAMA_VIDEO_MODEL=$MODEL_DIR/Wan-AI/Wan2.2-I2V-A14B" >> .env
  fi
fi

if [ "$WITH_TTS" = "1" ]; then
  echo "下载 CosyVoice 配音模型与官方代码"
  pip_install modelscope
  python3 - "$MODEL_DIR" <<'PY'
import sys
root = sys.argv[1]
try:
    from modelscope import snapshot_download
    for mid in ["iic/CosyVoice2-0.5B"]:
        try:
            p = snapshot_download(mid, cache_dir=root)
            print("downloaded:", p)
        except Exception as e:
            print(f"[warn] {mid} 下载失败：{e}")
            print(f"      可手动：modelscope download --model {mid} --local_dir {root}")
except ImportError:
    print("modelscope 未安装")
PY
  if [ ! -d "$DATA_DIR/repos/CosyVoice" ]; then
    git clone --depth 1 https://github.com/FunAudioLLM/CosyVoice \
      "$DATA_DIR/repos/CosyVoice" 2>/dev/null \
      || echo "[warn] clone 失败，请手动下载后设置 AUTODRAMA_COSYVOICE_DIR"
  fi
  {
    echo "AUTODRAMA_TTS=worker"
    echo "AUTODRAMA_TTS_BACKEND=cosyvoice"
    echo "AUTODRAMA_COSYVOICE_DIR=$DATA_DIR/repos/CosyVoice"
    echo "AUTODRAMA_COSYVOICE_MODEL=$MODEL_DIR/iic/CosyVoice2-0.5B"
  } >> .env
  echo "还需装官方依赖（CosyVoice 版本迭代快，依赖冲突请优先用命令模板兜底）："
  echo "  cd $DATA_DIR/repos/CosyVoice && pip install -r requirements.txt"
fi

if [ "$WITH_MODELS" = "1" ]; then
  echo "下载出图模型 SDXL（角色/场景首帧图）"
  python3 - "$MODEL_DIR" <<'PY'
import sys
root = sys.argv[1]
try:
    from modelscope import snapshot_download
    p = snapshot_download("AI-ModelScope/stable-diffusion-xl-base-1.0", cache_dir=root)
    print("downloaded:", p)
except Exception as e:
    print("下载失败，可手动执行：", e)
PY
  echo "AUTODRAMA_IMAGE=local" >> .env
fi

cat <<EOF

================ 环境就绪 ================

下一步（写码/审本用无卡开机，只有跑生成才开 GPU）：

  python3 -m autodrama init --name demo --idea "你的创意" --episodes 6
  python3 -m autodrama run -p demo --ep 1 --until shots   # 先人工确认剧本与分镜
  export AUTODRAMA_IMAGE=local AUTODRAMA_VIDEO=worker     # 用真实模型出图出视频
  python3 -m autodrama run -p demo --ep 1                 # 跑到成片

视频后端说明：
  wan  = diffusers 图生视频，接口稳定，建议先跑通    （AUTODRAMA_VIDEO_BACKEND=wan）
  h3   = MiniMax H3，走官方脚本；脚本接口变了就覆盖命令模板：
         export AUTODRAMA_H3_CMD='python \$AUTODRAMA_H3_DIR/infer.py --image "{image}" --prompt "{prompt}" --out "{out}"'
  所有视频生成都走 scripts/video_worker.py 批量入口：一次加载模型跑完整集，
  不会每个镜头都重载权重（那会多烧半小时 GPU 时间）。

配音：
  export AUTODRAMA_TTS=worker            # CosyVoice 批量配音（一次加载模型跑完整集）
  音色一致性：每个角色固定一份参考音频，全剧复用同一个 voice_sample。

角色 LoRA（主角专用，一致性最强）：
  python3 scripts/train_lora.py --project demo --character lin_wan --update-project
  数据来源是本项目的角色候选图/黄金参考图，prompt 直接用角色卡里的【锁定】外貌词。

安全提醒：
  - 跑完在控制台【关机】，关机不丢数据、停止计费
  - 存镜像前务必：rm -f .env
  - 代码请 git push，别只留在实例上
EOF
