#!/usr/bin/env bash
# AutoDrama · AutoDL 一键环境脚本（5090 32G / Ubuntu）
#
# 用法：
#   bash setup_autodl.sh                 # 基础：ffmpeg + 依赖 + 目录 + .env
#   bash setup_autodl.sh --gpu           # 加装 GPU 渲染依赖（torch/diffusers）
#   bash setup_autodl.sh --gpu --models  # 再下载图像模型到数据盘
#
# 设计原则：
#   - 代码放系统盘，模型与素材放 /root/autodl-tmp（数据盘，关机不丢）
#   - pip 多镜像自动回退（清华被限流时不会卡死）
#   - API Key 用 read -s 交互式写入，不进命令历史、不进 GitHub
set -e

DATA_DIR=/root/autodl-tmp
WITH_GPU=0
WITH_MODELS=0
for arg in "$@"; do
  case $arg in
    --gpu)    WITH_GPU=1 ;;
    --models) WITH_GPU=1; WITH_MODELS=1 ;;
  esac
done

SUDO=""
[ "$(id -u)" -ne 0 ] && SUDO="sudo"

echo "==> 0/6 环境自检"
python3 --version || { echo "缺少 python3"; exit 1; }
if command -v nvidia-smi >/dev/null 2>&1; then
  nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
else
  echo "未检测到 GPU（无卡开机模式），只能跑 LLM 与合成阶段"
fi

echo "==> 1/6 安装 ffmpeg 与中文字体（合成必需，中文不指定字体会画不出字）"
if command -v ffmpeg >/dev/null 2>&1; then
  echo "ffmpeg 已存在：$(ffmpeg -version | head -1)"
else
  $SUDO apt-get update -qq && $SUDO apt-get install -y -qq ffmpeg fonts-noto-cjk
fi

echo "==> 2/6 安装 Python 核心依赖"
pip_install() {
  for m in https://pypi.tuna.tsinghua.edu.cn/simple \
           https://mirrors.aliyun.com/pypi/simple/ \
           https://pypi.org/simple; do
    if python3 -m pip install "$@" -i "$m"; then return 0; fi
    echo "    镜像 $m 失败，换下一个"
  done
  return 1
}
python3 -m pip install --upgrade pip -q 2>/dev/null || true
pip_install -r requirements.txt

if [ "$WITH_GPU" = "1" ]; then
  echo "==> 3/6 安装 GPU 渲染依赖（torch/diffusers，较大）"
  pip_install -r requirements-gpu.txt
else
  echo "==> 3/6 跳过 GPU 依赖（需要时：bash setup_autodl.sh --gpu）"
fi

echo "==> 4/6 准备数据盘目录（关机不丢）"
mkdir -p "$DATA_DIR/models" "$DATA_DIR/cache"

echo "==> 5/6 生成 .env"
# 找一个可用的中文字体
FONT=""
for f in /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc \
         /usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc \
         /usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc; do
  [ -f "$f" ] && FONT="$f" && break
done
[ -z "$FONT" ] && FONT=$(fc-list :lang=zh 2>/dev/null | head -1 | cut -d: -f1)

if [ ! -f .env ]; then
  {
    echo "# Generated by setup_autodl.sh"
    echo "AUTODRAMA_DATA_ROOT=$DATA_DIR"
    echo "AUTODRAMA_MODEL_DIR=$DATA_DIR/models"
    echo "AUTODRAMA_FONT=$FONT"
    echo "DEEPSEEK_BASE_URL=https://api.deepseek.com"
    echo "DEEPSEEK_MODEL=deepseek-flash"
    echo "DEEPSEEK_MAX_TOKENS=16384"
  } > .env
  echo "已生成 .env（字体：$FONT）"
else
  echo ".env 已存在，跳过"
fi

if ! grep -q "DEEPSEEK_API_KEY=sk" .env 2>/dev/null; then
  echo ""
  echo "请粘贴你的 DeepSeek API Key（输入不回显，只写入本机 .env，不会进 GitHub）："
  read -s DSK
  if [ -n "$DSK" ]; then
    echo "DEEPSEEK_API_KEY=$DSK" >> .env
    echo "已写入 .env"
  else
    echo "未输入，稍后可手动：echo 'DEEPSEEK_API_KEY=sk-xxx' >> .env"
  fi
  unset DSK
fi

if [ "$WITH_MODELS" = "1" ]; then
  echo "==> 6/6 下载图像模型到数据盘（ModelScope，国内直连快）"
  pip_install modelscope
  python3 - <<'PY'
import os
root = os.environ.get("AUTODRAMA_MODEL_DIR", "/root/autodl-tmp/models")
try:
    from modelscope import snapshot_download
    for mid in ["AI-ModelScope/stable-diffusion-xl-base-1.0"]:
        p = snapshot_download(mid, cache_dir=root)
        print("downloaded:", p)
except Exception as e:
    print("模型下载失败，可稍后手动执行：", e)
PY
else
  echo "==> 6/6 跳过模型下载（需要时：bash setup_autodl.sh --models）"
fi

cat <<EOF

================ 环境就绪 ================

下一步（只在"跑生成"时开 GPU，写码审本用无卡开机）：

  # 1) 生成到分镜，人工确认剧本后再往下跑
  python3 -m autodrama init --name demo --idea "你的创意" --episodes 6
  python3 -m autodrama run -p demo --ep 1 --until shots

  # 2) 确认无误，跑完整条线（图像→视频→配音→合成）
  python3 -m autodrama run -p demo --ep 1

  # 3) 想用真实图像模型：
  #    export AUTODRAMA_IMAGE=local
  #    export AUTODRAMA_IMAGE_MODEL=\$AUTODRAMA_MODEL_DIR/AI-ModelScope/stable-diffusion-xl-base-1.0

安全提醒：
  - 跑完记得在控制台【关机】，关机不丢数据、停止计费
  - 存镜像前务必删除 .env：rm -f .env
  - 代码请 git push，不要只留在实例上
EOF
